### ISSUE TITLE
Detalles

### ISSUE THREAD

**Issue by nasivuela** [Adalab/d-s1-evaluacion-intermedia-MariaFCamino#11]
Buen trabajo @MariaFCamino !!!

¿Apañamos unos detallitos y le ponemos el broche final?

¿Hacemos mobile first? ¿Eeenn, y esto que era? Pues básicamente que ponemos todos los estilos para la versión móvil sin media queries, y estas la añadimos para los tamaños más grandes. Como en la descripción del proyecto nos decian que la versión tablet es a partir de 768px, lo que hariamos sería:
- Que la versión móvil se vea bien desde el tamaño más pequeñito hasta 767px (sin media queries)
- Poner `@media all and (min-width:768px) {}` y dentro todos los estilos para la versión tablet (y desktop en este caso ya que son iguales). Y así se verá bien desde 768px hasta la pantalla más grande que pueda tener una usuaria com mucho money para comprarse un pantallón ;)

Parace que nos hemos pasado con el alto, 100vh en la etiqueta `main` + la altura del header hace que nos pasemos de alto y aparezca un scroll innecesario, para arreglarlo tendriamos que:
- Hacer que `body` o (una etiqueta madre de `header` y `main`) ocupe todo el alto (vh mola :)
- Si a esta etiqueta madre le damos un display flex con la dirección adecuada, `header` y `main` serán items flex. ¿Se te ocurre alguna manera de decirle al item flex `main` que crezca  y ocupe todo el alto disponible?

A por ello!

**Comment by MariaFCamino** [comment]
Hola Nasi! Gracias por tus observaciones, son de gran ayuda para mí ;) 
Tengo un problema con el alto del contenido (main), no logro que se ajuste y desaparezca el scroll. He quitado márgenes, he aplicado el flex grow, he colocado el 100vh en el body y no sé que falla. Me echas una mano? ...muchas gracias!

**Comment by nasivuela** [comment]
@MariaFCamino Parece que has cambiado el nombre del css en el enlace del index. Cuando lo arregles podré echarle un ojo a lo que me comentas ;)

**Comment by MariaFCamino** [comment]
Perdona, ayer se me pasó linkearlo correctamente. Pero aquí lo tienes! ;)

**Comment by nasivuela** [comment]
Ojo, que igual se te ha pasado hacer `add`, `commit` o `push`.

**Comment by MariaFCamino** [comment]
Oh no! vaya despiste... bueno, esta sí que sí.

**Comment by nasivuela** [comment]
Ok, @MariaFCamino el scroll aparace por el modelo de caja. recuerda que con el modelo de caja por defecto (content-box) cuando definimos un alto o ancho de caja, el padding o borde que pongamos se añadira haciendola más grande. en tu caso al alto de 100vh del body se le añade un padding que has puesto en el body!

- Te dejo otro apunte, cuando nos dan un diseño para la versión movil por ejemplo con un tamaño de 320px, no significa que solo tenga que aplicarse a ese tamaño. Aplicaremos ese diseño en la maqueta hasta el siguiente breakpoint, por ejemplo el de tablet a 768px. He visto que en la versión móvil le has puesto a tu cabecera un ancho fijo. Esto hace que al agrandar la pantalla entre 320 y 767 la cabecera no se centre. mejor quitar ese ancho fijo y asegurarnos de que se ve como en la versión movil en todos los tamaños, hasta llegar a 768px.

Si es un poco liosa la explicación lo vemos luego ;)

**Comment by MariaFCamino** [comment]
Hola Nasi! He mirado los detalles y creo que mi proyecto (por fin) está decente. Aquí te lo dejo para que le puedas echar un vistazo. 
Muchas gracias por tu ayuda!
