### ISSUE TITLE
Herencia

### ISSUE THREAD

**Issue by nasivuela** [Adalab/d-s1-evaluacion-intermedia-MariaFCamino#7]
¿Le damos cariño a la herencia?
Podemos empezar por ponerle algunas declaraciones generales al body, para que otros selectores las hereden.

Por ejemplo: el tamaño de fuente (que será el que más se use en la página, por ejemplo 16px), la familia y el color.

**Comment by MariaFCamino** [comment]
Hola Nasi, he puesto en el <body> el margen 0 y el tipo de letra. No incluí el tamaño porque cambia en el <header> y en el <main> y al poner mediaqueries. Lo mismo con el color de la fuente. Lo dejo así o lo cambio, tú qué crees?

**Comment by nasivuela** [comment]
Puedes dejarlo así, para el futuro ya sabes si lo pones al principio todo irá mejor ;)
